apiVersion: v1
kind: Secret
metadata:
    name: anby
    namespace: apps
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:O/L8Xya2u5XvDvwf4cuMdG8LjyrdlbyC+EF/M7X3srgQWRAbhB+rpt5kqQH7DePB64qBbGCpBH2BLl6op99HTsMSkb8LmsJFcJ656axbCOxI5vnoy8IUqIxPsDQJp2qC9jjAB21szbq1Ylr99gcbax+hpESCmGAn1H2YxcJ1,iv:MdEM0QTsnKUdT119x4f5dpdlwkFLha0BuNB2BDxCNHk=,tag:i+TuqotZxfO7F5FHx26l1A==,type:str]
    TMDB_API_KEY: ENC[AES256_GCM,data:5V37BPjK2te3+XpHh0brF4ixDxJc0NfTZuASN9TID4I=,iv:/OMocEYK2Vf9CQQJbIirHodRgJ7VliPOVIpDnK7eDrY=,tag:9+zfHHGzp1bTPr10j6N0/w==,type:str]
    PROWLARR_API_KEY: ENC[AES256_GCM,data:bVwU42LCl9qEgFU5wXxyi0veuAVXOyIOF75oWCoSwhYSEskDLu1+cwl4FDrRgmlDyGN4CP5jdmWSeW0FAH+hmg==,iv:tnFfFY6m+KzGdgOisFzY12BN5YIywv9d6oi//WHKJjs=,tag:mIgSk+h0tI+MLFn7oDsgPA==,type:str]
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:5kVoWOyXluAOwlXaM+W3S5K5o75BgbFHJElLTSW7wOMnr0yiWzc7BlEyNZimRw==,iv:/2Q6xlstOp8pFRE2+j7ElCiyD/iX4MPaL43Y8t5fK/I=,tag:jq9ZmKAU/Cfqa4Ts3pwQ6w==,type:str]
    QBITTORRENT_USERNAME: ENC[AES256_GCM,data:4nDMn3Q=,iv:FCOFHilTg/EHziMXnLmCYUNJFQIp+wM2wuYBIFMdTqc=,tag:2OMLBPw/9RawAZdbZyNNWQ==,type:str]
    QBITTORRENT_PASSWORD: ENC[AES256_GCM,data:MoJOCL/lBUiV7Q==,iv:i/P1khpAA+9QeZdbROPoLi5tCJEogbte9KIgYfcU1rA=,tag:9qDNt8yaIyDSybrkMQc4Wg==,type:str]
sops:
    age:
        - recipient: age194r4u78jlkcg3waxh5ddpwe6y0pwenuhk9avnkmc3huzcpf26d0spa3ggf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXU0N5TGU5enNCOE1hclQy
            aktrVCsxWmhLbVEvNHJoeTVHNkNxeWN6NHd3CnIxMFRPRkd5RWdzTWQrUzl3bDFJ
            R01ieFpTeFk0WjEwd1NubzdWaGRGbDgKLS0tIDkvVi9MU2Yrc0cvVXVoRWpLemVH
            SE5vQlVIZDArdEdDTDREajJxVGIwSlEKZYbVV9c/DX805FIsWQgurKO36XSCUpD9
            GpaSWw8GJA7yRnxw0lUTxOOTPBxriI3fIhNlKo+gK+NCH552SI/WEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T17:08:41Z"
    mac: ENC[AES256_GCM,data:Je3dnOgSE2FgESxykUs8BhRfKc/8m3RFAxzmbnBHAtPwe4GXing6IfkzmqelfzxufnjHeFQTOdkhu5yX17xkfopo0Iz1SHOTC0MELpGSBdVEj3tmY4ba0+FOyUa3VsGtk0Ks/LQXsi/sTWQ106KfRSq6IYOkOyr9yB1ZHKOJo88=,iv:gp4i8uGylLjRiDsuJmFndxRDCRLJdWIdLdZRk2i6LtY=,tag:ECRDPT+82fjpprLAqLtFkQ==,type:str]
    encrypted_regex: ((?i)(pass($|word)|claim|secret($|[^N])|key|token|^data$|^stringData|^databaseUrl))
    version: 3.11.0
