---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app mosquitto
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: apps
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      mosquitto:
        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
        initContainers:
          init-config:
            image:
              repository: public.ecr.aws/docker/library/eclipse-mosquitto
              tag: 2.1.2-alpine
            command:
              - /bin/sh
              - -c
            args:
              - |
                cp /mosquitto/secret/mosquitto_pwd /mosquitto/external_config/mosquitto_pwd
                chmod 600 /mosquitto/external_config/mosquitto_pwd
                mosquitto_passwd -U /mosquitto/external_config/mosquitto_pwd
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities:
                drop: ["ALL"]
            resources:
              requests:
                cpu: 10m
                memory: 32Mi
              limits:
                memory: 64Mi
        containers:
          app:
            image:
              repository: public.ecr.aws/docker/library/eclipse-mosquitto
              tag: 2.1.2-alpine
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: &port 1883
                  periodSeconds: 10
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop: ["ALL"]
            resources:
              requests:
                cpu: 10m
                memory: 32Mi
              limits:
                memory: 128Mi

    service:
      app:
        controller: mosquitto
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: "192.168.5.15"
        externalTrafficPolicy: Local
        ports:
          mqtt:
            port: *port

    persistence:
      data:
        type: persistentVolumeClaim
        storageClass: longhorn
        accessMode: ReadWriteOnce
        size: 512Mi
        advancedMounts:
          mosquitto:
            app:
              - path: /mosquitto/data
      config:
        type: configMap
        name: mosquitto
        advancedMounts:
          mosquitto:
            app:
              - path: /mosquitto/config/mosquitto.conf
                subPath: mosquitto.conf
                readOnly: true
      secret:
        type: secret
        name: mosquitto
        advancedMounts:
          mosquitto:
            init-config:
              - path: /mosquitto/secret
                readOnly: true
      external-config:
        type: emptyDir
        advancedMounts:
          mosquitto:
            init-config:
              - path: /mosquitto/external_config
            app:
              - path: /mosquitto/external_config
                readOnly: true

    configMaps:
      config:
        data:
          mosquitto.conf: |
            per_listener_settings false
            listener 1883
            allow_anonymous false
            persistence true
            persistence_location /mosquitto/data
            autosave_interval 1800
            connection_messages true
            password_file /mosquitto/external_config/mosquitto_pwd
