apiVersion: v1
kind: Secret
metadata:
    name: mosquitto
    namespace: apps
type: Opaque
stringData:
    mosquitto_pwd: ENC[AES256_GCM,data:NGlHgh5ceaM5eNdQp+qD0RxLFH3n/Rk5YfchDg==,iv:M1DsoFDKnGvx65CC6rri6e7EO3SJG4IIt7p72dQReeQ=,tag:oKmHTqUEzYRy9G8la+oKAg==,type:str]
sops:
    age:
        - recipient: age194r4u78jlkcg3waxh5ddpwe6y0pwenuhk9avnkmc3huzcpf26d0spa3ggf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1cVlRTGd3bEwxYUV1NnNZ
            Vk9MWHZFR0psUWZzbVV1YURMZWhNUjNHRHhVCkpvL3VDTnkwODcyWHFQU3VVM3gv
            K3JXWWs0YnNUcmNUeFJhWk9XOVBhQ3MKLS0tIHMwcHNGREZ6ZVVaL09sUDhVMUt2
            bkxsbFp4WGc4aCtXR1UrWTEzTXl1NkkKGO9nfxNpi6SnCO2vD96Wvbw8ZFVhY9sN
            L8H7aAMd1B9dfPwyQLdaypjzDi7MX78iA9X3iw0LDslbSFCRq2vA0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-18T20:28:51Z"
    mac: ENC[AES256_GCM,data:wcZfMj8SUTSQIAFuGkTPpBBSd/efdcGWziGi7Q/nHodoV3VwC68o77nTU+b4kJFiqb8klRukI9Buj+uanj4CMw2CHbLu2exjA85WJR2Ia6NX7h76O7C4CStcrGsTUnel6SwWTM5D5B8hOaI1sjZAbNKX6Fv319tb3SasA7PchMU=,iv:FBHVo1SDRz7e2LnQHj6dYueRbYzJg+jDu9D3AclL1bU=,tag:qJ+h+ydPDXdFYvsIaa9FJQ==,type:str]
    encrypted_regex: ((?i)(pass($|word)|claim|secret($|[^N])|key|token|^data$|^stringData|^databaseUrl))
    version: 3.11.0
